/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Action */
        post: operations["create_action"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity */
        get: operations["get_activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/{activity_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo Action */
        post: operations["undo_action"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google Callback */
        post: operations["google_callback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/briefing/items/{briefing_item_id}/remind_later": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remind Later */
        post: operations["remind_later"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/briefing/items/{briefing_item_id}/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Item Seen */
        post: operations["mark_item_seen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/briefing/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today Briefing */
        get: operations["today_briefing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cleanup Queue */
        get: operations["get_cleanup_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cleanup/{proposal_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Approve Cleanup */
        post: operations["post_approve_cleanup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake/pubsub": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pubsub Webhook
         * @description Pub/Sub push webhook. Always acks with 200 once auth passes — even a
         *     duplicate or orphan (no matching active source) notification is a
         *     normal outcome, not an error (mail_intake.md "[멱등]"/"[빈상태]"), so
         *     Pub/Sub doesn't retry-storm us.
         */
        post: operations["pubsub_webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake/sources/{source_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manual Sync
         * @description Manual resync trigger. Route is mounted under this router's /intake
         *     prefix (app/api/router.py), giving POST /intake/sources/{id}/sync — see
         *     this domain's final report for why the literal path in
         *     _integration-contract.md §3 ("POST /sources/{id}/sync", no /intake
         *     prefix) couldn't be used without splitting `router` into two exposed
         *     symbols, which §4's single-`router`-per-domain contract doesn't allow.
         */
        post: operations["manual_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Labels */
        get: operations["get_labels"];
        put?: never;
        /** Create Label */
        post: operations["create_label"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labels/{label_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Label */
        patch: operations["patch_label"];
        trace?: never;
    };
    "/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Message Detail */
        get: operations["message_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{message_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move Message */
        post: operations["move_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notifications */
        get: operations["get_notifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subscribe Endpoint */
        post: operations["subscribe_endpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rules */
        get: operations["get_rules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{suggestion_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Approve Rule */
        post: operations["post_approve_rule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources"];
        put?: never;
        /** Connect Source */
        post: operations["connect_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["get_source"];
        put?: never;
        post?: never;
        /** Disconnect Source */
        delete: operations["disconnect_source"];
        options?: never;
        head?: never;
        /** Patch Source Settings */
        patch: operations["patch_source_settings"];
        trace?: never;
    };
    "/storage/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Storage Upcoming */
        get: operations["storage_upcoming"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountBriefingGroup */
        AccountBriefingGroup: {
            /**
             * Connected Account Id
             * Format: uuid
             */
            connected_account_id: string;
            /** Gmail Address */
            gmail_address: string;
            /** Items */
            items: components["schemas"]["BriefingCard"][];
            /** Status */
            status: string;
            /** Syncing */
            syncing: boolean;
        };
        /** ActivityLogEntry */
        ActivityLogEntry: {
            /** Action Summary */
            action_summary: string;
            /** Actor Id */
            actor_id: string | null;
            /** Command Id */
            command_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Undo Available */
            undo_available: boolean;
            /** Undone At */
            undone_at: string | null;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * BriefingCard
         * @description Today-briefing / card list shape.
         *
         *     Deliberately excludes any Gmail mutation action, AI judgement reason,
         *     or raw body field — briefing.md "카드 응답에는 Gmail mutation action,
         *     AI 판단 이유, raw body를 넣지 않는다" (강제 invariant). Tests assert
         *     field *absence*, not null values, so no such field is declared here.
         */
        BriefingCard: {
            /**
             * Connected Account Id
             * Format: uuid
             */
            connected_account_id: string;
            /** Done */
            done: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Importance Band */
            importance_band: string | null;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /**
             * Rebuilt At
             * Format: date-time
             */
            rebuilt_at: string;
            /** Received At */
            received_at: string | null;
            /** Section */
            section: string;
            /** Seen */
            seen: boolean;
            /** Sender */
            sender: string | null;
            /** Snippet */
            snippet: string | null;
            /** Subject */
            subject: string | null;
            /** Summary Text */
            summary_text: string | null;
        };
        /** ClassificationRule */
        ClassificationRule: {
            /** Active */
            active: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Match Condition */
            match_condition: {
                [key: string]: unknown;
            };
            /**
             * Service Label Id
             * Format: uuid
             */
            service_label_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** CleanupProposal */
        CleanupProposal: {
            /** After State */
            after_state: {
                [key: string]: unknown;
            } | null;
            /** Before State */
            before_state: {
                [key: string]: unknown;
            };
            /** Confidence Band */
            confidence_band: string;
            /** Decided At */
            decided_at: string | null;
            /** Gmail Action Command Id */
            gmail_action_command_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /** Proposed Action */
            proposed_action: string;
            /** Status */
            status: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** ConnectSourceRequest */
        ConnectSourceRequest: {
            /** Access Token */
            access_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Gmail Address */
            gmail_address: string;
            /** Refresh Token */
            refresh_token: string;
            /** Scope */
            scope: string;
        };
        /** ConnectedSource */
        ConnectedSource: {
            /**
             * Connected At
             * Format: date-time
             */
            connected_at: string;
            /** Display Name */
            display_name: string | null;
            /** Gmail Address */
            gmail_address: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** CreateActionRequest */
        CreateActionRequest: {
            /** Action Type */
            action_type: string;
            /**
             * Connected Account Id
             * Format: uuid
             */
            connected_account_id: string;
            /** Gmail Label Id */
            gmail_label_id?: string | null;
            /** Message Id */
            message_id?: string | null;
        };
        /** CreateLabelRequest */
        CreateLabelRequest: {
            /**
             * Connected Account Id
             * Format: uuid
             */
            connected_account_id: string;
            /**
             * Hidden
             * @default false
             */
            hidden: boolean;
            /** Name */
            name: string;
            /** Order Index */
            order_index?: number | null;
        };
        /** DisconnectResult */
        DisconnectResult: {
            /**
             * Connected Account Id
             * Format: uuid
             */
            connected_account_id: string;
            /** Status */
            status: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            }[] | {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** GmailActionCommand */
        GmailActionCommand: {
            /** Action Type */
            action_type: string;
            /** Applied At */
            applied_at: string | null;
            /** Changed */
            changed: boolean | null;
            /**
             * Connected Account Id
             * Format: uuid
             */
            connected_account_id: string;
            /** Error Reason */
            error_reason: string | null;
            /** Failed At */
            failed_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Message Id */
            message_id: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /**
             * Requested By
             * Format: uuid
             */
            requested_by: string;
            /** Status */
            status: string;
            /** Version */
            version: number;
        };
        /** GoogleCallbackRequest */
        GoogleCallbackRequest: {
            /** Id Token */
            id_token: string;
        };
        /** GoogleCallbackResponse */
        GoogleCallbackResponse: {
            /** Is New User */
            is_new_user: boolean;
            /** Token */
            token: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** ItemStateResult */
        ItemStateResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /** Remind Later At */
            remind_later_at: string | null;
            /** Seen */
            seen: boolean;
            /** Seen At */
            seen_at: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** ManualSyncQueued */
        ManualSyncQueued: {
            /** Job Type */
            job_type: string;
            /** Queued */
            queued: boolean;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
        };
        /** ManualSyncRequest */
        ManualSyncRequest: {
            /**
             * Run Type
             * @default delta
             * @enum {string}
             */
            run_type: "delta" | "full";
        };
        /**
         * MessageDetail
         * @description GET /messages/{id} readonly view.
         *
         *     No mutation action field (mark_read/archive/label) and no AI reason
         *     field by default — briefing.md "Read API" §negative / §빈상태.
         */
        MessageDetail: {
            /**
             * Connected Account Id
             * Format: uuid
             */
            connected_account_id: string;
            /** Done */
            done: boolean;
            /** Excerpt Text */
            excerpt_text: string | null;
            /** Gmail Message Id */
            gmail_message_id: string;
            /** Gmail Thread Id */
            gmail_thread_id: string;
            /** Gmail Url */
            gmail_url: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Importance Band */
            importance_band: string | null;
            /** Received At */
            received_at: string | null;
            /** Sender */
            sender: string | null;
            /** Subject */
            subject: string | null;
            /** Summary Text */
            summary_text: string | null;
        };
        /** MoveMessageRequest */
        MoveMessageRequest: {
            /**
             * Label Id
             * Format: uuid
             */
            label_id: string;
        };
        /** MoveMessageResult */
        MoveMessageResult: {
            /**
             * Correction Signal Id
             * Format: uuid
             */
            correction_signal_id: string;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /**
             * Service Label Id
             * Format: uuid
             */
            service_label_id: string;
            /** Version */
            version: number;
        };
        /** NotificationEvent */
        NotificationEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notification Type */
            notification_type: string;
            /** Read At */
            read_at: string | null;
            route_target: components["schemas"]["RouteTarget"];
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** NotificationSubscription */
        NotificationSubscription: {
            /** Endpoint */
            endpoint: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Revoked At */
            revoked_at: string | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** PubSubAckResponse */
        PubSubAckResponse: {
            /** Deduped */
            deduped: boolean;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /** Checks */
            checks: {
                [key: string]: string;
            };
            /** Status */
            status: string;
        };
        /** RemindLaterRequest */
        RemindLaterRequest: {
            /**
             * Remind At
             * Format: date-time
             */
            remind_at: string;
        };
        /** ReminderResult */
        ReminderResult: {
            /**
             * Briefing Item State Id
             * Format: uuid
             */
            briefing_item_state_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reactivated At */
            reactivated_at: string | null;
            /**
             * Remind At
             * Format: date-time
             */
            remind_at: string;
            /** Status */
            status: string;
        };
        /**
         * RouteTarget
         * @description "어느 화면 + 어느 selected item" — notifications.md 매핑표의 결과 shape.
         *
         *     `screen` is always present (generic-landing-prohibition invariant —
         *     notifications.md "route_target이 비면(selected item 부재는 허용, 화면
         *     부재는 불가) 발행을 거부한다"). `item_id` may be None for screen-only
         *     notifications (e.g. daily_briefing).
         */
        RouteTarget: {
            /** Item Id */
            item_id?: string | null;
            /** Screen */
            screen: string;
        };
        /** RuleSuggestion */
        RuleSuggestion: {
            /**
             * Correction Signal Id
             * Format: uuid
             */
            correction_signal_id: string;
            /** Decided At */
            decided_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Suggested Condition */
            suggested_condition: {
                [key: string]: unknown;
            };
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * RulesView
         * @description GET /rules response shape — pending suggestions + active rules.
         */
        RulesView: {
            /** Rules */
            rules: components["schemas"]["ClassificationRule"][];
            /** Suggestions */
            suggestions: components["schemas"]["RuleSuggestion"][];
        };
        /** ServiceLabel */
        ServiceLabel: {
            /**
             * Connected Account Id
             * Format: uuid
             */
            connected_account_id: string;
            /** Gmail Label Id */
            gmail_label_id: string | null;
            /** Gmail Label Name */
            gmail_label_name: string;
            /** Hidden */
            hidden: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Order Index */
            order_index: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** SessionSummaryResponse */
        SessionSummaryResponse: {
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Workspace Name */
            workspace_name: string | null;
        };
        /** SourceSettingsResult */
        SourceSettingsResult: {
            /** Briefing Enabled */
            briefing_enabled: boolean;
            /**
             * Connected Account Id
             * Format: uuid
             */
            connected_account_id: string;
            /** Display Name */
            display_name: string | null;
            /** Effective Display Name */
            effective_display_name: string;
            /** Gmail Address */
            gmail_address: string;
            /** Notification Enabled */
            notification_enabled: boolean;
            /** Paused */
            paused: boolean;
            /** Status */
            status: string;
            /** Summary Enabled */
            summary_enabled: boolean;
        };
        /** SubscribeRequest */
        SubscribeRequest: {
            /** Endpoint */
            endpoint: string;
            /** Keys */
            keys: {
                [key: string]: unknown;
            };
        };
        /** UndoResult */
        UndoResult: {
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Original Command Id
             * Format: uuid
             */
            original_command_id: string;
            /** Reverse Command Id */
            reverse_command_id: string | null;
            /** Undo Available */
            undo_available: boolean;
            /** Undone At */
            undone_at: string | null;
        };
        /** UpcomingReminderEntry */
        UpcomingReminderEntry: {
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /**
             * Remind At
             * Format: date-time
             */
            remind_at: string;
            /**
             * Reminder Id
             * Format: uuid
             */
            reminder_id: string;
        };
        /** UpcomingStorage */
        UpcomingStorage: {
            /** This Week */
            this_week: components["schemas"]["UpcomingReminderEntry"][];
            /** Today */
            today: components["schemas"]["UpcomingReminderEntry"][];
            /** Tomorrow */
            tomorrow: components["schemas"]["UpcomingReminderEntry"][];
        };
        /** UpdateLabelRequest */
        UpdateLabelRequest: {
            /** Hidden */
            hidden?: boolean | null;
            /** Name */
            name?: string | null;
            /** Order Index */
            order_index?: number | null;
        };
        /** UpdateSourceSettingsRequest */
        UpdateSourceSettingsRequest: {
            /** Briefing Enabled */
            briefing_enabled?: boolean | null;
            /** Display Name */
            display_name?: string | null;
            /** Notification Enabled */
            notification_enabled?: boolean | null;
            /** Paused */
            paused?: boolean | null;
            /** Summary Enabled */
            summary_enabled?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_action: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GmailActionCommand"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_activity: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityLogEntry"][];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    undo_action: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UndoResult"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    google_callback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleCallbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleCallbackResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_session: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummaryResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remind_later: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                briefing_item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemindLaterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderResult"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    mark_item_seen: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                briefing_item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemStateResult"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    today_briefing: {
        parameters: {
            query?: {
                scope?: string;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountBriefingGroup"][];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_cleanup_queue: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupProposal"][];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_approve_cleanup: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupProposal"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    pubsub_webhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PubSubAckResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    manual_sync: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualSyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualSyncQueued"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_labels: {
        parameters: {
            query?: {
                include_hidden?: boolean;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceLabel"][];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_label: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLabelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceLabel"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_label: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                label_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLabelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceLabel"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    message_detail: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    move_message: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                authorization?: string;
            };
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveMessageResult"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_notifications: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationEvent"][];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    subscribe_endpoint: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSubscription"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    get_rules: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulesView"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_approve_rule: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSuggestion"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_sources: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectedSource"][];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    connect_source: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectSourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectedSource"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_source: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectedSource"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    disconnect_source: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisconnectResult"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_source_settings: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSourceSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSettingsResult"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    storage_upcoming: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpcomingStorage"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Maily error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
